"""Initial schema

Revision ID: 004a2ed8d59f
Revises: 
Create Date: 2026-08-22 16:12:34.963974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004a2ed8d59f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_v2',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.String(), nullable=True),
    sa.Column('purchase_record_id', sa.String(), nullable=True),
    sa.Column('gst_record_id', sa.String(), nullable=True),
    sa.Column('deterministic_decision', sa.String(), nullable=True),
    sa.Column('deterministic_score', sa.Float(), nullable=True),
    sa.Column('deterministic_coverage', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('calibrated_ml_probability', sa.Float(), nullable=True),
    sa.Column('graph_features', sa.String(), nullable=True),
    sa.Column('evidence_features', sa.String(), nullable=True),
    sa.Column('final_human_decision', sa.String(), nullable=True),
    sa.Column('reviewer_action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('explanation_version', sa.String(), nullable=True),
    sa.Column('rag_context_identifiers', sa.String(), nullable=True),
    sa.Column('legacy_payload', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_feedback_v2_packet_id'), 'feedback_v2', ['packet_id'], unique=False)
    op.create_index(op.f('ix_feedback_v2_review_id'), 'feedback_v2', ['review_id'], unique=False)
    op.create_index(op.f('ix_feedback_v2_tenant_id'), 'feedback_v2', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_v2_tenant_id'), table_name='feedback_v2')
    op.drop_index(op.f('ix_feedback_v2_review_id'), table_name='feedback_v2')
    op.drop_index(op.f('ix_feedback_v2_packet_id'), table_name='feedback_v2')
    op.drop_table('feedback_v2')
    # ### end Alembic commands ###
